# Generated by Django 6.0.1 on 2026-02-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='google_doc_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
