# Generated by Django 6.0.2 on 2026-02-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_header_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='about/')),
            ],
        ),
    ]
