# Generated by Django 6.0.2 on 2026-02-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='content_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='content_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='google_doc_url',
            field=models.URLField(blank=True),
        ),
    ]
